#pragma once
std::map<unsigned int, unsigned int> textures;
OpenGLResourceManager    resourceManager;
GeometryFactory          geometryFactory;
IMaterial*               depthMat;
IMaterial*               rectMat;
IMaterial*               postProcessMat;
IMaterial*               deferredShadingMat;
IMaterial*               deferredShadingRectMat[4];
shared_ptr<Rectangle>    r;
shared_ptr<Rectangle>    postProcessRect;
shared_ptr<Rectangle>    deferredShadingRect[4];
FrameBuffer*             fb;
FrameBuffer*             postProcessFbo;
FrameBuffer*             deferredShadingFbo;
ITexture*                shadowMap;
ITexture*                postProcessTex;
ITexture*                deferredShadingTex[3];
PerspectiveCamera        lightCamera;
Vec2                     resolution;
shared_ptr<IMaterialProperty<int>> dsColorMap;
shared_ptr<IMaterialProperty<int>> dsNormalMap;
shared_ptr<IMaterialProperty<int>> dsDepthMap;
void initDeferredShading();
void initPostProcessing();
void initShadowMapping();
unsigned int depthRenderBuffer;
void render(std::vector<IMesh*>& meshes, ICamera& camera);
void render(IMesh* mesh, ICamera& camera);
void updateUniforms(const IMaterial& material);
void renderToTexture(std::vector<IMesh*>& meshes, ICamera& camera, Vec4& viewport = Vec4(0, 0, 0, 0));
void renderWithPostProcess(std::vector<IMesh*>& meshes, ICamera& camera);
void renderDeferred(std::vector<IMesh*>& meshes, ICamera& camera);
void postProcess(std::vector<IMesh*>& meshes, ICamera& camera);
